# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f58c165ed54115e8e7c1796ea2682c09775e94cb8f47bd8d02c7327957e1d9513973f7713a155f142b27c5889d5e3931d43fd4d08d45a96cb3c3db9659a54465

test:
  secret_key_base: 5956d75ffcd4fb190de242d81af315781692f65e33c121de763092a9e5dbf24c5fe2b8ec526a657a55b1748d7b9742e6d2b897bf48ccddc965e961f987cd7ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
